corpid:
  yinian: wwd3728ae0a7ede18d
secret:
  contact: 2pxT7wDgi6enryLPgGh7oveK8CScAeldtmm2LIVwdsk
  custorm: xxxxxx
dev:
  BASE_URL: https://dev.qyapi.weixin.qq.com/cgi-bin
prod:
  BASE_URL: https://qyapi.weixin.qq.com/cgi-bin
